################################################################################
# SSH configuration for Gitea access using an agenix-managed development key.
#
# This is for headless hosts that have their own SSH keypair (generated by
# agenix-rekey) rather than relying on agent-forwarded keys from a workstation.
################################################################################
{ facts, ... }:
{
  programs.ssh = {
    settings = {
      "gitea.${facts.network.domain}" = {
        Port = 2222;
        User = "git";
        IdentityFile = "/run/agenix/logan-dev-ssh";
        IdentitiesOnly = true;
      };
    };
  };
}
