################################################################################
# Development identity for logan on headless hosts.
#
# This layers development capabilities (git config, SSH key for Gitea, GPG
# signing subkey) on top of logan-server.nix (which linux-host.nix already
# imports).  Import this file from any headless host that should be able to
# commit, sign, and push code as logan.
#
# Prerequisites (manual, one-time):
#   1. Run the GPG ceremony described in the plan to create a signing subkey.
#   2. Export the public key to keys/logan-gpg-public.asc.
#   3. Encrypt the secret subkey with rage for agenix.
#   4. Fill in the real subkey fingerprint below (replacing the placeholder).
#   5. Register secrets/generated/logan-dev-ssh.pub with the Gitea account.
################################################################################
{
  config,
  flake-inputs,
  lib,
  pkgs,
  system,
  ...
}:
{
  imports = [
    ../nixos-configs/user-can-develop.nix
  ];

  # home.nix expects `system` (e.g. for flake-inputs.*.packages.${system}),
  # but linux-host.nix doesn't include it in extraSpecialArgs.
  home-manager.extraSpecialArgs = {
    inherit system;
  };
  # Use the system-level nixpkgs (and its unfree predicates) for home-manager
  # packages.  darwin.nix sets this for macOS hosts; NixOS hosts need it
  # explicitly when importing home.nix.
  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;

  # gnupg is needed on PATH for interactive commit signing.  The systemd
  # import service uses full store paths, but git invokes gpg by name.
  # pass is the interactive password store.  After deploying, clone the store
  # manually:
  #   git clone ssh://git@gitea.proton:2222/logan/logan-pass.git ~/.password-store
  environment.systemPackages = [
    pkgs.gnupg
    pkgs.pass
  ];

  # Provide the git-users argument consumed by git-config.nix (imported
  # transitively via user-can-develop.nix).
  _module.args.git-users = [
    {
      git-email = "logustus@gmail.com";
      git-name = "Logan Barnett";
      git-signing-key = "437343BA2E1B25D1";
      host-username = "logan";
    }
  ];

  home-manager.users.logan = {
    imports = [
      (import ../home.nix)
      ../home-configs/ssh-config-general.nix
      ../home-configs/ssh-config-proton.nix
      ../home-configs/ssh-config-gitea-dev-key.nix
    ];
  };

  # ── agenix secrets ──────────────────────────────────────────────────────────

  # Ed25519 keypair generated by agenix-rekey.  The public half lands in
  # secrets/generated/logan-dev-ssh.pub and must be registered with Gitea.
  age.secrets.logan-dev-ssh = {
    generator.script = "ssh-ed25519-with-pub";
    mode = "0600";
    owner = "logan";
  };

  # Manually encrypted GPG secret subkey (signing-only).  Encrypt with:
  #   rage -e -i secrets/agenix-master-key-3.age \
  #     -o secrets/logan-gpg-signing-subkey.age /tmp/logan-signing-subkey.gpg
  age.secrets.logan-gpg-signing-subkey = {
    rekeyFile = ../secrets/logan-gpg-signing-subkey.age;
    mode = "0600";
    owner = "logan";
  };

  # ── GPG key import ──────────────────────────────────────────────────────────

  # Oneshot service that imports both the public keyring (from the repo) and
  # the secret signing subkey (from agenix) into logan's GPG keyring.  Runs
  # once per boot after agenix has decrypted secrets.
  systemd.services.import-gpg-signing-key = {
    description = "Import GPG signing key for logan";
    wantedBy = [ "multi-user.target" ];
    after = [ "agenixInstall.service" ];
    wants = [ "agenixInstall.service" ];
    serviceConfig = {
      Type = "oneshot";
      User = "logan";
      Group = "users";
      ExecStart =
        let
          script = pkgs.writeShellScript "import-gpg-signing-key" ''
            set -euo pipefail
            export GNUPGHOME="/home/logan/.gnupg"
            mkdir -p "$GNUPGHOME"
            chmod 700 "$GNUPGHOME"
            ${pkgs.gnupg}/bin/gpg --batch --import ${../gpg-keys/logan-gpg-public.asc}
            ${pkgs.gnupg}/bin/gpg --batch --import ${config.age.secrets.logan-gpg-signing-subkey.path}
          '';
        in
        "${script}";
      RemainAfterExit = true;
    };
  };
}
