################################################################################
# Authelia SSO/OIDC provider for the proton network.
#
# Authelia acts as the single identity provider for all OIDC-enabled services
# declared in facts.network.services.  It authenticates against the network
# LDAP directory and issues tokens to registered clients.
#
# Storage lives in PostgreSQL (peer auth, Unix socket — no password exchange).
# All secrets are delivered via systemd LoadCredential.
################################################################################
{
  config,
  facts,
  host-id,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib) pipe;
  inherit (lib.attrsets)
    attrNames
    filterAttrs
    mapAttrsToList
    ;
  inherit (lib.strings) concatLines concatMapStrings;
  inherit (pkgs.callPackage ../lib/yaml.nix { }) indentLines;

  # The instance service name is authelia (prefix) and (authelia) the instance.
  service-name = "authelia-authelia";

  services = facts.network.services or { };
  users = facts.network.users or { };

  credName = name: "${name}-oidc-client-secret";

  port = 9091;

  # The agenix secret name for the LDAP bind password, auto-generated by the
  # ldap-auth module when auth.ldap.users."${host-id}-authelia-service" is
  # declared.
  ldapCredName = "${host-id}-authelia-service-ldap-password";

  oidcServices = filterAttrs (
    name: value: (services.${name}.authentication or null) == "oidc"
  ) services;

  # Produce the YAML block for a single OIDC client.  All lines are at
  # 0–4 spaces so that after indentLines 6 the layout aligns under
  # `clients:` (which sits at 4 spaces in the header block):
  #
  #       - client_id: ...          (6 spaces = 0 + 6)
  #         client_name: ...        (8 spaces = 2 + 6)
  #         redirect_uris:          (8 spaces = 2 + 6)
  #           - https://...         (10 spaces = 4 + 6)
  #         scopes:                 (8 spaces = 2 + 6)
  #           - openid              (10 spaces = 4 + 6)
  #
  # Using explicit string concatenation (not ''...'' multiline literals)
  # avoids the Nix indentation-stripping edge cases that arise when
  # interpolated content sits at column 0.
  mkClientYaml =
    name: svc:
    let
      oidcUserName = name;
      hasConfidential =
        (users ? ${oidcUserName})
        && (users.${oidcUserName}.type or "") == "oidc-client";
      redirectUriLines = concatMapStrings (uri: "    - ${uri}\n") (
        svc.redirectUris or [
          "https://${svc.fqdn}/oauth2/callback"
          "https://${svc.fqdn}/auth/callback"
        ]
      );
    in
    "- client_id: ${if hasConfidential then oidcUserName else name}\n"
    + "  client_name: ${svc.description or name}\n"
    + "  redirect_uris:\n"
    + redirectUriLines
    + "  scopes:\n"
    + "    - openid\n"
    + "    - profile\n"
    + "    - email\n"
    + "    - groups\n"
    + "  authorization_policy: one_factor\n"
    + "  consent_mode: implicit\n"
    + "  public: ${lib.boolToString (!hasConfidential)}\n"
    + "  require_pkce: ${lib.boolToString (!hasConfidential)}\n"
    + (
      if hasConfidential then
        # 2-space prefix → 8 spaces after indentLines 6, aligning with the
        # other mapping keys (client_name, redirect_uris, etc.).
        "  client_secret: %${credName name}%\n"
        + "  token_endpoint_auth_method: ${
            svc.tokenEndpointAuthMethod or "client_secret_post"
          }\n"
      else
        ""
    );

  # The Authelia OIDC provider YAML fragment injected via settingsFiles.
  # Includes the JWKS with the private key embedded as a YAML double-quoted
  # string.  The generator writes the PEM with literal \n sequences; after
  # template substitution the YAML double-quoted string `key: "...\n..."` is
  # parsed by the YAML library into a real multi-line PEM — the only form
  # Authelia accepts (no file-path syntax or _FILE env var for this field).
  clientYaml = ''
    identity_providers:
      oidc:
        jwks:
          - key_id: default
            algorithm: RS256
            use: sig
            key: "%${host-id}-authelia-oidc-private-key%"
        clients:
  ''
  + (pipe oidcServices [
    (mapAttrsToList mkClientYaml)
    (builtins.map (indentLines 6))
    concatLines
  ]);

in
{
  networking.dnsAliases = [
    "authelia"
    "sso"
  ];
  # LDAP service account for Authelia's bind DN.  Declaring the user here
  # causes the ldap-auth module to auto-generate two agenix secrets:
  #   ${host-id}-authelia-service-ldap-password        (plaintext passphrase)
  #   ${host-id}-authelia-service-ldap-password-hashed (slapd hash)
  # The reconciler keeps the LDAP entry's userPassword in sync automatically.
  auth.ldap.users."${host-id}-authelia-service" = {
    fullName = "${host-id}-authelia-service";
    description = "Authelia LDAP bind account on ${host-id}.";
  };

  # Grant the Authelia service account write access to userPassword so it can
  # perform password resets on behalf of users.
  services.ldap-server.passwordWriteDNs = [
    "uid=${host-id}-authelia-service,ou=users,dc=proton,dc=org"
  ];

  # The NixOS authelia module runs the service as "authelia-<instance>", i.e.
  # "authelia-authelia".  PostgreSQL peer auth requires the OS user and the
  # database user to match exactly, so we use the same name for both.
  services.postgresql = {
    enable = true;
    ensureDatabases = [ "authelia-authelia" ];
    ensureUsers = [
      {
        name = "authelia-authelia";
        ensureDBOwnership = true;
      }
    ];
  };

  # RSA-4096 private key generator for Authelia's OIDC JWKS.
  #
  # Authelia requires the key as inline PEM in the YAML config; there is no
  # file-path reference syntax and no supported _FILE env var for this field.
  # The template-file substitution is a literal string replace, so multi-line
  # PEM content would break the YAML indentation.
  #
  # Workaround: store the PEM with literal \n sequences (two chars: backslash
  # then n) instead of real newlines, then embed it in a YAML double-quoted
  # string in clientYaml.  The YAML parser converts \n → newline, giving
  # Authelia a valid PEM.
  age.generators.rsa-private-key =
    { pkgs, ... }:
    ''
      set -euo pipefail
      ${pkgs.openssl}/bin/openssl genpkey \
        -algorithm RSA \
        -pkeyopt rsa_keygen_bits:4096 \
        2>/dev/null \
        | ${pkgs.gnused}/bin/sed ':a;N;$!ba;s/\n/\\n/g'
    '';

  age.secrets = {
    "${host-id}-authelia-oidc-private-key" = {
      generator.script = "rsa-private-key";
    };
    "${host-id}-authelia-storage-key" = {
      generator.script = "hex";
      settings.length = 64;
    };
    "${host-id}-authelia-jwt-secret" = {
      generator.script = "hex";
      settings.length = 64;
    };
    "${host-id}-authelia-session-secret" = {
      generator.script = "hex";
      settings.length = 64;
    };
    "${host-id}-authelia-oidc-secrets-config.yaml" = {
      generator = {
        script = "template-file";
        dependencies = [
          config.age.secrets."${host-id}-authelia-oidc-private-key"
        ]
        ++ mapAttrsToList (name: _: config.age.secrets."${credName name}") oidcServices;
      };
      settings.template = clientYaml;
    };
  };

  services.https.fqdns."authelia.${facts.network.domain}" = {
    enable = true;
    internalPort = port;
  };

  services.authelia.instances.authelia = {
    enable = true;
    secrets = {
      storageEncryptionKeyFile = "/run/credentials/${service-name}.service/storage-encryption-key";
      jwtSecretFile = "/run/credentials/${service-name}.service/jwt-secret";
      sessionSecretFile = "/run/credentials/${service-name}.service/session-secret";
    };
    settingsFiles = [
      "/run/credentials/${service-name}.service/authelia-oidc-secrets-config"
    ];
    settings = {
      theme = "dark";
      authentication_backend = {
        ldap = {
          # Using ldap.${facts.network.domain} because that is the CN on the TLS certificate.
          address = "ldaps://ldap.${facts.network.domain}";
          timeout = "20 seconds";
          start_tls = false;
          base_dn = "dc=proton,dc=org";
          additional_users_dn = "ou=users";
          additional_groups_dn = "ou=groups";
          # Allow login by either uid (username) or mail address.
          users_filter = "(&(objectClass=inetOrgPerson)(|({username_attribute}={input})({mail_attribute}={input})))";
          # Forward lookup: find all groupOfNames entries that list the
          # user's DN in their member attribute.  Does not require the
          # memberOf overlay.
          groups_filter = "(&(objectClass=groupOfNames)(member={dn}))";
          attributes = {
            username = "uid";
            mail = "mail";
            display_name = "cn";
            group_name = "cn";
          };
          # Bind DN; password delivered via
          # AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE.
          user = "uid=${host-id}-authelia-service,ou=users,dc=proton,dc=org";
        };
      };
      access_control = {
        default_policy = "deny";
        rules = mapAttrsToList (name: data: {
          domain = data.fqdn;
          subject = builtins.map (g: "group:${g}") (data.groups or [ ]);
          policy = "one_factor";
        }) facts.network.services;
      };
      notifier = {
        smtp = {
          # Connect via loopback — both services are on the same host.
          # Using the DNS name would route through the LAN IP, which
          # Stalwart rate-limits independently.
          address = "submission://localhost:587";
          username = "${host-id}-authelia-service";
          sender = "Authelia <${host-id}-authelia-service@${facts.network.domain}>";
          tls = {
            server_name = "mail.${facts.network.domain}";
            # Both services run on the same host; the internal CA cert is not
            # in the system trust store and Authelia's SMTP TLS has no
            # trusted_certificates option.
            skip_verify = true;
          };
        };
      };
      server = {
        address = "tcp://127.0.0.1:${toString port}/login";
      };
      session = {
        cookies = [
          {
            authelia_url = "https://authelia.${facts.network.domain}/login/";
            default_redirection_url = "https://authelia.${facts.network.domain}";
            # "proton" is on the public suffix list so a wildcard cookie
            # domain is not possible.  The session cookie lives on
            # authelia.proton; OIDC flows redirect through here so other
            # services don't need to share the cookie directly.
            domain = "authelia.${facts.network.domain}";
          }
        ];
      };
      storage = {
        # Peer auth via Unix socket — PostgreSQL accepts the connection
        # because the OS user "authelia" matches the database user.  No
        # password exchange occurs; the empty string is a no-op.
        # `address` replaces the deprecated host/port pair as of 4.38.0.
        postgres = {
          address = "unix:///run/postgresql";
          database = "authelia-authelia";
          username = "authelia-authelia";
          password = "";
          schema = "public";
        };
      };

      # ── Role claim for Immich (commented out — see paper trail below) ──
      #
      # WHAT WE WANT
      # ─────────────
      # Immich supports OIDC role promotion via `roleClaim`.  If the named
      # OIDC claim has the value "admin", the user gets admin privileges;
      # any other value (or absence of the claim) yields a regular user.
      # We want admins who are in the `immich-admins` LDAP group to
      # receive this treatment automatically on login.
      #
      # WHY IT IS NOT WIRED UP
      # ───────────────────────
      # Authelia's `claims_policies` can only copy a static LDAP attribute
      # value into a claim — it has no expression engine to COMPUTE "if
      # user is in group X, emit 'admin'; otherwise emit 'user'".
      # There is no Authelia-side way to map group membership to an
      # arbitrary string claim value as of 4.39.x.
      #
      # The correct fix is to store the role as a custom LDAP attribute
      # (e.g. `immichRole: admin`) on admin users, backed by an auxiliary
      # object class added to the inetOrgPerson schema, then map it here.
      # That is a separate project requiring LDAP schema extension and
      # reconciliation for every user in facts.
      #
      # IMMICH DOES NOT HELP
      # ─────────────────────
      # Immich has no built-in "members of group X are admins" feature.
      # The feature request tracking this gap (group-to-role mapping) is:
      #   https://github.com/immich-app/immich/issues/24097
      # It was not shipped as of 2026-03.
      #
      # The Immich NixOS module also does not expose `roleClaim` as a
      # module option at time of writing, so wiring it declaratively
      # requires either an upstream patch or a raw config file injection
      # (which we already have via IMMICH_CONFIG_FILE / immich-oauth-config).
      #
      # HOW TO RE-ENABLE WHEN READY
      # ────────────────────────────
      # 1. Extend the LDAP schema with an auxiliary object class that adds
      #    an `immichRole` attribute (DirectoryString, single-valued).
      # 2. Reconcile `immichRole` for every user in facts (admins → "admin",
      #    others → "user").
      # 3. Uncomment the identity_providers block below.
      # 4. Add `"claims_policy": "immich-role-policy"` to the Immich entry
      #    in mkClientYaml (or the clientYaml settingsFile template).
      # 5. Add `"roleClaim": "immich_role"` to immichOauthConfigTemplate in nixos-configs/immich.nix.
      # 6. Run `agenix rekey generate --rekey -a` to regenerate secrets.
      # 7. Grant admin manually in the Immich UI for the bootstrap user
      #    (one-time, before step 3 is deployed).
      #
      # CURRENT STANCE
      # ───────────────
      # Admin status is granted once manually in the Immich UI after the
      # first OIDC login.  Regular users self-register (autoRegister: true)
      # and receive the default "user" role automatically.

      # identity_providers = {
      #   oidc = {
      #     claims_policies = {
      #       immich-role-policy = {
      #         id_token = [
      #           {
      #             name = "immich_role";
      #             attribute = "immichRole";
      #           }
      #         ];
      #       };
      #     };
      #   };
      # };
    };
  };

  # Define a host-local "OIDC provider is serving" target so consumers can
  # depend on the abstraction instead of authelia-authelia-ready.service
  # directly.  Parallels nss-lookup.target / ldap-ready.target.
  systemd.targets.oidc-ready = {
    description = "OIDC provider is up and serving discovery";
  };

  # Readiness gate: blocks dependent services until Authelia's HTTP health
  # endpoint responds.  systemd considers authelia-authelia.service "started"
  # the instant the process forks (Type=simple), but Authelia still needs to
  # run DB migrations, bind to LDAP, and initialise OIDC.  Services that
  # perform OIDC discovery at startup (oauth2-proxy, org-wiki-web) depend on
  # oidc-ready.target instead of authelia-authelia.service directly.
  systemd.services."${service-name}-ready" = {
    description = "Wait for Authelia to become healthy";
    after = [ "${service-name}.service" ];
    requires = [ "${service-name}.service" ];
    wants = [ "oidc-ready.target" ];
    before = [ "oidc-ready.target" ];
    # Couple target lifecycle to authelia-ready so restarts propagate.  See
    # the matching comment in nixos-configs/blocky.nix for the reasoning.
    unitConfig.PropagatesStopTo = "oidc-ready.target";
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      # Poll the internal listener directly (no DNS or TLS dependency).
      ExecStart = pkgs.writeShellScript "wait-for-authelia" ''
        until ${pkgs.curl}/bin/curl -sf http://127.0.0.1:${toString port}/api/health >/dev/null 2>&1; do
          sleep 1
        done
      '';
      # Give Authelia a generous window — DB migrations on first boot can be
      # slow.  If this fires, something is genuinely broken.
      TimeoutStartSec = 120;
    };
  };

  # TODO: Upstream the authelia NixOS module to use postgresql.target when a
  # postgresql storage backend is configured, so we can drop the manual ordering.
  systemd.services.${service-name} =
    let
      after = [
        "ldap-ready.target"
        "nss-lookup.target"
        "postgresql.target"
        "run-agenix.d.mount"
      ];
    in
    {
      inherit after;
      requires = after;
      # Restart whenever any loaded credential's .age file changes (i.e. after
      # rekeying).  The .file attribute is the Nix store path to the rekeyed
      # .age file; it changes every time the secret is regenerated, which
      # causes NixOS to treat this unit as new and restart it.
      restartTriggers =
        (builtins.map (name: config.age.secrets."${credName name}".file) (
          attrNames oidcServices
        ))
        ++ [
          config.age.secrets."${host-id}-authelia-storage-key".file
          config.age.secrets."${host-id}-authelia-jwt-secret".file
          config.age.secrets."${host-id}-authelia-session-secret".file
          config.age.secrets."${host-id}-authelia-oidc-secrets-config.yaml".file
          config.age.secrets.${ldapCredName}.file
        ];
      environment = {
        # The NixOS authelia module has no ldapAdminPasswordFile option.
        # Deliver the LDAP bind password via LoadCredential and point
        # Authelia to the credential path via this env var.
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE = "/run/credentials/${service-name}.service/ldap-password";
        AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE = "/run/credentials/${service-name}.service/ldap-password";
      };
      serviceConfig = {
        LoadCredential =
          (builtins.map (
            name:
            # Parentheses allow characters that are otherwise illegal in a
            # systemd credential name (e.g. hyphens in compound names).
            "(${credName name}):${config.age.secrets."${credName name}".path}"
          ) (attrNames oidcServices))
          ++ [
            "storage-encryption-key:${
              config.age.secrets."${host-id}-authelia-storage-key".path
            }"
            "jwt-secret:${config.age.secrets."${host-id}-authelia-jwt-secret".path}"
            "session-secret:${config.age.secrets."${host-id}-authelia-session-secret".path}"
            "authelia-oidc-secrets-config:${
              config.age.secrets."${host-id}-authelia-oidc-secrets-config.yaml".path
            }"
            "ldap-password:${config.age.secrets.${ldapCredName}.path}"
          ];
      };
    };

  systemd.tmpfiles.rules = [
    "d /var/lib/${service-name} 0750 authelia authelia -"
  ];

  # Goss health checks for Authelia.
  services.goss.checks = {
    # Check that the HTTPS endpoint is responding.  Authelia serves the
    # login page at the root.
    http."https://authelia.${facts.network.domain}/" = {
      status = 200;
      timeout = 5000;
    };
    # Check that the API health endpoint works.
    http."https://authelia.${facts.network.domain}/api/health" = {
      status = 200;
      timeout = 3000;
    };
    # Check that the internal authelia port is listening.
    port."tcp:${toString port}" = {
      listening = true;
      ip = [ "127.0.0.1" ];
    };
    # Check that HTTPS port is listening (handled by reverse proxy).
    port."tcp:443" = {
      listening = true;
    };
    # Check that the authelia service is running.
    service.${service-name} = {
      enabled = true;
      running = true;
    };
  };
}
