################################################################################
# FreeRADIUS — 802.1X / WPA-Enterprise authentication for the proton network.
#
# Gives WiFi clients per-user logins (EAP-TTLS, inner PAP) verified against the
# network LDAP directory, instead of a single shared WPA-Personal passphrase.
# Runs on silicon, co-located with the LDAP and PostgreSQL it talks to.
#
# AUTHENTICATION MODEL
# ────────────────────
# A device connects, the access point relays the EAP exchange to this server,
# and this server says yes/no.  The inner method is PAP carried inside the TTLS
# TLS tunnel, so the client sends its cleartext password to us privately; we
# then verify it by BINDING to LDAP *as that user*.  Binding (not reading the
# stored hash) is the only method compatible with the directory's argon2
# userPassword hashes, which are one-way and cannot be read back for
# comparison.  Consequently — unlike Authelia — the bind account needs no write
# access to userPassword; it is used only for the authorize-phase lookup
# (resolve the user DN, check group membership), an ordinary read.
#
# ACCOUNTING
# ──────────
# RADIUS accounting (session start/stop) is written to PostgreSQL via peer auth
# over the Unix socket (same pattern as Authelia — no password exchanged).  The
# radacct table is what a future Simultaneous-Use alert (Grafana → ntfy) reads
# to count active devices per user and warn on a device-budget overrun that
# persists past a dwell window.  See nixos-configs/freeradius-facts.nix for the
# per-user device registry and AP client list once that work lands.
#
# STATUS — UNVALIDATED UNTIL HARDWARE EXISTS
# ──────────────────────────────────────────
# The NixOS freeradius module is deliberately thin — it only runs
# `radiusd -d <configDir>`.  We build that configDir (the `raddb` derivation
# below) by overlaying our six decision files (nixos-configs/freeradius/*) onto
# the upstream example tree.  Those files are the canonical recipes for
# LDAP-bind auth + TTLS + SQL accounting, but a FreeRADIUS config is only truly
# landed by iterating with `radiusd -X` against a live authenticator — and
# there is no access point to authenticate against until the AP hardware is
# installed.  Treat the raddb as a reviewed starting point, not a proven
# config.  Two prerequisites before this even builds/imports cleanly:
#   1. Run agenix generate for this host so the EAP leaf cert
#      (../secrets/tls-radius.proton.crt) exists — the raddb derivation reads it.
#   2. Load the radacct schema into the `radius` database once (the upstream
#      schema ships in the raddb at mods-config/sql/main/postgresql/schema.sql).
# Per-AP clients and per-user device limits live in freeradius-facts.nix.
################################################################################
{
  config,
  facts,
  host-id,
  lib,
  pkgs,
  ...
}:
let
  domain = facts.network.domain;
  radius-fqdn = "radius.${domain}";
  base-dn = "dc=proton,dc=org";

  # The OS user the NixOS freeradius module runs radiusd as.  It must match the
  # PostgreSQL role below so accounting can use peer auth over the Unix socket
  # (same approach as Authelia).  CONFIRM against the nixpkgs freeradius module
  # before first deploy — if upstream uses a different name, update both this
  # binding and services.postgresql.ensureUsers.
  radius-user = "radius";

  # Plaintext bind passphrase, auto-generated by the ldap-auth module when the
  # auth.ldap.users."${host-id}-freeradius-service" entry below is declared.
  ldap-bind-passphrase = "${host-id}-freeradius-service-ldap-password";

  # rlm_ldap takes its bind password as an inline `password = "..."` directive
  # with no file-reference option.  Rather than bake the secret into the
  # world-readable raddb in the Nix store, wrap it in a one-line include file
  # via the template-file generator (the same trick Authelia uses for its OIDC
  # secrets) and $INCLUDE it from mods-enabled/ldap.  The file is delivered
  # under /run/credentials via LoadCredential, which is populated before
  # radiusd parses its config at startup.
  ldap-bind-include = "${host-id}-freeradius-ldap-bind.conf";

  # The assembled raddb.  The NixOS freeradius module is deliberately thin — it
  # only runs `radiusd -d <configDir>` — so we build the config tree here by
  # overlaying our six decision files (./freeradius/*) onto the upstream example
  # tree.  Upstream provides the dictionary, policy.d, the SQL schema/queries,
  # and the inner-tunnel skeleton; we own only the files that encode our
  # choices (LDAP auth, TTLS, our CA cert, SQL accounting, clients).
  #
  # The public EAP certificate and CA are copied into certs/ (store paths — safe
  # to read); the private key is delivered separately via LoadCredential.  DH
  # params are generated at build time so the EAP TLS config has a dh_file
  # without depending on the upstream certs/ bootstrap script.
  #
  # NOTE: this evaluates only once the EAP leaf cert exists — run agenix
  # generate for this host (which produces ../secrets/tls-${radius-fqdn}.crt)
  # before building.  And it is UNVALIDATED until landed with `radiusd -X`
  # against a live authenticator — there is no AP to test against yet.
  raddb = pkgs.runCommandLocal "freeradius-raddb" { } ''
    cp -a ${pkgs.freeradius}/etc/raddb $out
    chmod -R u+w $out

    install -m 0644 ${./freeradius/mods-available/eap}           $out/mods-available/eap
    install -m 0644 ${./freeradius/mods-available/ldap}          $out/mods-available/ldap
    install -m 0644 ${./freeradius/mods-available/sql}           $out/mods-available/sql
    install -m 0644 ${./freeradius/sites-available/default}      $out/sites-available/default
    install -m 0644 ${./freeradius/sites-available/inner-tunnel} $out/sites-available/inner-tunnel
    install -m 0644 ${./freeradius/clients.conf}                 $out/clients.conf

    # eap, and the default + inner-tunnel sites, are already enabled upstream;
    # ldap and sql ship disabled, so enable them.
    ln -sf ../mods-available/ldap $out/mods-enabled/ldap
    ln -sf ../mods-available/sql  $out/mods-enabled/sql

    install -m 0644 ${../secrets/tls-${radius-fqdn}.crt} $out/certs/radius.crt
    install -m 0644 ${../secrets/proton-ca.crt}          $out/certs/ca.pem
    ${pkgs.openssl}/bin/openssl dhparam -out $out/certs/dh 2048 2>/dev/null
  '';
in
{
  networking.dnsAliases = [ "radius" ];

  # EAP server certificate for the TTLS outer tunnel, tied to the internal CA.
  # Clients are provisioned to trust the proton CA and pin this server identity
  # (radius.proton), so a rogue server impersonating the SSID can't harvest
  # inner-tunnel passwords.
  tls.tls-leafs.${radius-fqdn} = {
    fqdn = radius-fqdn;
    ca = config.age.secrets.proton-ca;
  };

  # LDAP bind (service) account.  Declaring it here makes the ldap-auth module
  # generate the bind passphrase secret and reconcile the directory entry.  See
  # the AUTHENTICATION MODEL note above for why this account needs no
  # userPassword write grant (contrast nixos-configs/authelia.nix).
  auth.ldap.users."${host-id}-freeradius-service" = {
    fullName = "${host-id}-freeradius-service";
    description = "FreeRADIUS LDAP bind account on ${host-id}.";
  };

  # One-line $INCLUDE snippet carrying the bind password, kept out of the store.
  age.secrets.${ldap-bind-include} = {
    generator = {
      script = "template-file";
      dependencies = [ config.age.secrets.${ldap-bind-passphrase} ];
    };
    settings.template = ''password = "%${ldap-bind-passphrase}%"'';
  };

  # Session accounting store.  Peer auth over the Unix socket: the radiusd OS
  # user matches this role, so no password is exchanged.  The radacct rows
  # written here back the per-user active-device counting the alerting relies
  # on.
  services.postgresql = {
    enable = true;
    ensureDatabases = [ "radius" ];
    ensureUsers = [
      {
        name = radius-user;
        ensureDBOwnership = true;
      }
    ];
  };

  services.freeradius = {
    enable = true;
    configDir = raddb;
  };

  # Deliver the EAP private key and the LDAP bind include to radiusd at runtime
  # without placing either in the Nix store.  The public certificate
  # (tls-${radius-fqdn}.crt) and the CA cert are store paths — safe to read
  # directly from the assembled raddb.
  systemd.services.freeradius = {
    serviceConfig.LoadCredential = [
      "radius-key:${config.age.secrets."tls-${radius-fqdn}.key".path}"
      "ldap-bind:${config.age.secrets.${ldap-bind-include}.path}"
    ];
    # Restart radiusd when any delivered secret is rekeyed (the .file path
    # changes on regeneration), matching the restartTrigger pattern used by the
    # other services on this host.
    restartTriggers = [
      config.age.secrets."tls-${radius-fqdn}.key".file
      config.age.secrets.${ldap-bind-include}.file
    ];
  };

  # 1812/udp = authentication, 1813/udp = accounting (RFC 2865 / RFC 2866).
  networking.firewall.allowedUDPPorts = [
    1812
    1813
  ];
}
