################################################################################
# Mastodon instances for silicon.
#
# Three separate federation identities, each with its own PostgreSQL database,
# Redis server, and set of systemd units:
#
#   proton    — mastodon.proton       (private, internal CA)
#   logustus  — mastodon.logustus.com (public, ACME)
#   meshward  — mastodon.meshward.com (public, ACME)
#
# All three use Authelia on authelia.proton as their OIDC provider.
# OMNIAUTH_ONLY disables password login; accounts are auto-provisioned on first
# OIDC login.
#
# SMTP routes through Stalwart on mail.proton:587 (authenticated submission).
# Each instance has its own LDAP service account so credentials are isolated.
################################################################################
{
  config,
  facts,
  lib,
  ...
}:
let
  autheliaFqdn = "authelia.${facts.network.domain}";

  # Non-sensitive OIDC environment variables for one instance.  The
  # OIDC_CLIENT_SECRET is sensitive and comes separately via extraEnvFiles.
  # OMNIAUTH_ONLY disables local password login entirely; all authentication
  # goes through Authelia.  New accounts are auto-provisioned on first login.
  mkOidcConfig = clientId: redirectFqdn: {
    OIDC_ENABLED = "true";
    OIDC_DISPLAY_NAME = "Authelia";
    OIDC_DISCOVERY = "true";
    OIDC_ISSUER = "https://${autheliaFqdn}";
    OIDC_SCOPE = "openid,profile,email";
    OIDC_UID_FIELD = "preferred_username";
    OIDC_CLIENT_ID = clientId;
    OIDC_REDIRECT_URI = "https://${redirectFqdn}/auth/auth/openid_connect/callback";
    OIDC_SECURITY_ASSUME_EMAIL_IS_VERIFIED = "true";
    OMNIAUTH_ONLY = "true";
  };

  # Produce an env-file agenix secret that exposes OIDC_CLIENT_SECRET for the
  # named OIDC service.  The base secret is generated by oidc-secrets.nix.
  mkOidcEnvSecret = serviceName: {
    generator = {
      script = "template-file";
      dependencies = [ config.age.secrets."${serviceName}-oidc-client-secret" ];
    };
    settings.template = "OIDC_CLIENT_SECRET=%${serviceName}-oidc-client-secret%\n";
  };

  # Produce an env-file agenix secret that exposes SMTP_LOGIN and SMTP_PASSWORD
  # for the named service account.  The password is the LDAP password
  # auto-generated by ldap-auth.nix; Stalwart authenticates via LDAP re-bind.
  mkSmtpEnvSecret = serviceName: {
    generator = {
      script = "template-file";
      dependencies = [ config.age.secrets."${serviceName}-ldap-password" ];
    };
    settings.template = "SMTP_LOGIN=${serviceName}\nSMTP_PASSWORD=%${serviceName}-ldap-password%\n";
  };
in
{
  imports = [
    ../nixos-modules/mastodon.nix
  ];
  networking.dnsAliases = [ "mastodon" ];

  # ── LDAP service accounts for SMTP authentication ──────────────────────────
  # One account per instance so credentials are isolated.  ldap-auth.nix
  # auto-emits <name>-ldap-password and <name>-ldap-password-hashed secrets.
  auth.ldap.users.mastodon-proton = {
    fullName = "Mastodon proton SMTP service account";
    type = "service";
    group = "mastodon-proton";
    managed = true;
  };
  auth.ldap.users.mastodon-logustus = {
    fullName = "Mastodon logustus SMTP service account";
    type = "service";
    group = "mastodon-logustus";
    managed = true;
  };
  auth.ldap.users.mastodon-meshward = {
    fullName = "Mastodon meshward SMTP service account";
    type = "service";
    group = "mastodon-meshward";
    managed = true;
  };

  # ── OIDC env-file secrets ──────────────────────────────────────────────────
  age.secrets."mastodon-proton-oidc-env" = mkOidcEnvSecret "mastodon-proton";
  age.secrets."mastodon-logustus-oidc-env" = mkOidcEnvSecret "mastodon-logustus";
  age.secrets."mastodon-meshward-oidc-env" = mkOidcEnvSecret "mastodon-meshward";

  # ── SMTP env-file secrets ───────────────────────────────────────────────────
  age.secrets."mastodon-proton-smtp-env" = mkSmtpEnvSecret "mastodon-proton";
  age.secrets."mastodon-logustus-smtp-env" = mkSmtpEnvSecret "mastodon-logustus";
  age.secrets."mastodon-meshward-smtp-env" = mkSmtpEnvSecret "mastodon-meshward";

  # ── Internal-CA TLS leaf for the .proton instance ─────────────────────────
  # The https module auto-generates this for FQDNs declared in
  # services.https.fqdns, but we are using configureNginx = true on the
  # mastodon module instead.  Declare the leaf manually so tls-leaf.nix
  # produces the cert and key secret.
  tls.tls-leafs."mastodon.${facts.network.domain}" = {
    fqdn = "mastodon.${facts.network.domain}";
    ca = config.age.secrets.proton-ca;
  };

  # ── Mastodon instances ─────────────────────────────────────────────────────
  services.mastodon.instances = {

    proton = {
      enable = true;
      localDomain = "mastodon.${facts.network.domain}";
      streamingProcesses = 1;
      configureNginx = true;
      smtp = {
        createLocally = false;
        host = "mail.${facts.network.domain}";
        port = 587;
        fromAddress = "mastodon@${facts.network.domain}";
      };
      extraConfig =
        mkOidcConfig "mastodon-proton" "mastodon.${facts.network.domain}"
        // {
          SMTP_ENABLE_STARTTLS = "always";
        };
      extraEnvFiles = [
        config.age.secrets."mastodon-proton-oidc-env".path
        config.age.secrets."mastodon-proton-smtp-env".path
      ];
    };

    logustus = {
      enable = true;
      localDomain = "mastodon.logustus.com";
      streamingProcesses = 1;
      configureNginx = true;
      smtp = {
        createLocally = false;
        host = "mail.${facts.network.domain}";
        port = 587;
        fromAddress = "mastodon@logustus.com";
      };
      extraConfig = mkOidcConfig "mastodon-logustus" "mastodon.logustus.com" // {
        SMTP_ENABLE_STARTTLS = "always";
      };
      extraEnvFiles = [
        config.age.secrets."mastodon-logustus-oidc-env".path
        config.age.secrets."mastodon-logustus-smtp-env".path
      ];
    };

    meshward = {
      enable = true;
      localDomain = "mastodon.meshward.com";
      streamingProcesses = 1;
      configureNginx = true;
      smtp = {
        createLocally = false;
        host = "mail.${facts.network.domain}";
        port = 587;
        fromAddress = "mastodon@meshward.com";
      };
      extraConfig = mkOidcConfig "mastodon-meshward" "mastodon.meshward.com" // {
        SMTP_ENABLE_STARTTLS = "always";
      };
      extraEnvFiles = [
        config.age.secrets."mastodon-meshward-oidc-env".path
        config.age.secrets."mastodon-meshward-smtp-env".path
      ];
    };
  };

  # ── nginx virtual host overrides ───────────────────────────────────────────
  # The mastodon module creates virtual hosts without listen directives, so
  # nginx would default to all interfaces.  Pin each to its domain-policy
  # address so SNI routing is correct and the private instance is not
  # reachable on the public IP.
  # Force DNS-01 for the public instances.  When nginx manages ACME directly
  # (enableACME = true) it creates a cert entry with webroot set, which
  # blocks security.acme.defaults.dnsProvider from taking effect and causes
  # HTTP-01 to be used instead.  Instead, we declare the certs explicitly
  # (empty attrs inherit all security.acme.defaults including dnsProvider and
  # credentialFiles) and tell nginx to use them via useACMEHost.
  security.acme.certs."mastodon.logustus.com" = {
    group = "nginx";
  };
  security.acme.certs."mastodon.meshward.com" = {
    group = "nginx";
  };

  # ── Split-horizon DNS ──────────────────────────────────────────────────────
  # Return the internal IP for the public instances so that clients on the LAN
  # bypass the router entirely, avoiding hairpin NAT.
  services.blocky.settings.customDNS.mapping = {
    "mastodon.logustus.com" = "192.168.254.100";
    "mastodon.meshward.com" = "192.168.254.100";
  };

  services.nginx.virtualHosts = {

    "mastodon.${facts.network.domain}" = {
      listen = [
        {
          addr = "192.168.254.9";
          port = 443;
          ssl = true;
        }
        {
          addr = "192.168.254.9";
          port = 80;
        }
      ];
      # Disable ACME; use internal CA leaf instead.  The mastodon module sets
      # enableACME = lib.mkDefault true (lower priority), so a plain false here
      # wins without needing mkForce.
      enableACME = false;
      sslCertificate = ../secrets/tls-mastodon.proton.crt;
      sslCertificateKey = config.age.secrets."tls-mastodon.proton.key".path;
    };

    "mastodon.logustus.com" = {
      listen = [
        {
          addr = "192.168.254.100";
          port = 443;
          ssl = true;
        }
        {
          addr = "192.168.254.100";
          port = 80;
        }
      ];
      enableACME = false;
      useACMEHost = "mastodon.logustus.com";
    };

    "mastodon.meshward.com" = {
      listen = [
        {
          addr = "192.168.254.100";
          port = 443;
          ssl = true;
        }
        {
          addr = "192.168.254.100";
          port = 80;
        }
      ];
      enableACME = false;
      useACMEHost = "mastodon.meshward.com";
    };
  };
}
