################################################################################
# Stalwart mail server configuration for silicon.
#
# Mail domains:
#   proton        Internal LAN-only; no external MX.
#   meshward.com  Business domain; external MX, DKIM-signed.
#   logustus.com  Personal domain; external MX, DKIM-signed, catch-all.
#
# Authentication is LDAP-backed against OpenLDAP on silicon.  The stalwart
# service account is declared here; ldap-auth.nix auto-emits its password
# secrets.
#
# Before first deploy, generate all secrets:
#   agenix rekey generate --rekey -a
# Then commit the generated secrets/tls-mail.proton.crt to the repository.
#
# After a DKIM secret is generated, extract the public key for the DNS TXT
# record at default._domainkey.<domain>:
#   openssl pkey -in <(rage --decrypt secrets/generated/stalwart-dkim-<domain>.age) \
#     -pubout | grep -v '^-----' | tr -d '\n'
################################################################################
{ facts, ... }:
let
  domain = facts.network.domain;
  baseDn = "dc=${domain},dc=org";
in
{
  # Register the stalwart LDAP service account.  ldap-auth.nix auto-emits:
  #   stalwart-ldap-password         — plaintext, delivered via LoadCredential
  #   stalwart-ldap-password-hashed  — argon2 hash for the LDAP reconciler
  auth.ldap.users.stalwart = {
    emails = [ "stalwart@${domain}" ];
    fullName = "Stalwart mail service account";
    type = "service";
    group = "stalwart-mail";
    managed = true;
  };

  # Ed25519 DKIM private keys.  rekeyFile is omitted so agenix-rekey places
  # them in secrets/generated/ automatically.
  age.secrets.stalwart-dkim-meshward = {
    generator.script = "stalwart-dkim-key";
  };
  age.secrets.stalwart-dkim-logustus = {
    generator.script = "stalwart-dkim-key";
  };

  services.stalwart-host = {
    enable = true;

    internalDomain = domain;

    externalDomains = [
      {
        domain = "meshward.com";
        dkimSelector = "default";
        dkimSecretName = "stalwart-dkim-meshward";
      }
      {
        domain = "logustus.com";
        dkimSelector = "default";
        dkimSecretName = "stalwart-dkim-logustus";
        catchAllTarget = "logustus@${domain}";
      }
    ];

    ldap = {
      url = "ldaps://ldap.${domain}:636";
      baseDn = baseDn;
    };

    internalTls = {
      # Generated by agenix-rekey via tls.tls-leafs in the module.  The .crt
      # is a plain file committed to the repo after running agenix rekey.
      certFile = "${../secrets/tls-mail.proton.crt}";
      keySecretName = "tls-mail.proton.key";
    };
  };

  # Let's Encrypt certificates for the external mail domains via Porkbun
  # DNS-01 challenge.  Stalwart uses SNI to select the cert matching the
  # connecting client's domain, so the cert name must match d.domain exactly
  # (the same value used in the module's certificate.${d.domain} stanza).
  # dnsProvider and credentialsFiles are inherited from security.acme.defaults
  # (configured in acme.nix).
  security.acme.certs."meshward.com" = {
    group = "stalwart-mail";
    postRun = "systemctl reload-or-restart stalwart-mail.service || true";
  };
  security.acme.certs."logustus.com" = {
    group = "stalwart-mail";
    postRun = "systemctl reload-or-restart stalwart-mail.service || true";
  };
}
